### ISSUE TITLE
change tool title to "Instructor Tools"

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/instructor-productivity-tools#305]
Change the application title to `Instructor Tools`

Change the Github repo name to `instructor-tools`

**Comment by jonespm** [comment]
I renamed this repository.

Canvas App Explorer is hardcoded many places in the code including directory names. Will take a little time to work on this to identify what low impact, user facing things can be changed and maybe leave some of the rest as-is.

**Comment by zqian** [comment]
I have renamed the GitHub project name to "Instructor Tools"
