### ISSUE TITLE
Apply workaround for oauth2 migration issue

### ISSUE THREAD

**Issue by jonespm** [tl-its-umich-edu/instructor-productivity-tools#371]
I'd filed this issue but it currently isn't fixed and we still see a warning
https://github.com/Harvard-University-iCommons/django-canvas-oauth/issues/3

Two options are suggested, ignored all migrations from this 
```
MIGRATION_MODULES = {
    'canvas_oauth': None,  # This disables migrations for the canvas_oauth package
}
```

Or add this migration locally. I think I'm going to choose the option to add it locally.

**Comment by zqian** [comment]
@jonespm Could you please include the Test steps?

**Comment by jonespm** [comment]
I don't think there's any user facing change. The migration adjusts verbose_name [which seems like it might be a bug (or at least unnecessary oddity) in Django](https://stackoverflow.com/questions/26503826/why-does-django-make-migrations-for-help-text-and-verbose-name-changes). There a lot of workarounds on that thread to avoid this type of change.

In any case the test would just be as @pushyamig tested on the PR

1. Ensure that canvas_oauth2_token is still created on an empty database
2. Ensure that an API key can be obtained through Oauth workflow
3. Ensure there's no warnings in the logs at startup about this canvas_oauth

This is all dev testing.
